#ifndef MY_SWITCH_H
#define MY_SWITCH_H 

#include "stm32f0xx_hal.h"
#include "main.h"
#include "my_global.h"
#include "my_tim.h"

//#define FA_SWITCH_OPEN   HAL_GPIO_WritePin(A_COMPRESS_IO_GPIO_Port, A_COMPRESS_IO_Pin, GPIO_PIN_SET)
//#define FA_SWITCH_CLOSE  HAL_GPIO_WritePin(A_COMPRESS_IO_GPIO_Port, A_COMPRESS_IO_Pin, GPIO_PIN_RESET)

//#define FB_SWITCH_OPEN   HAL_GPIO_WritePin(A_DENITROGEN_IO_GPIO_Port, A_DENITROGEN_IO_Pin, GPIO_PIN_SET)
//#define FB_SWITCH_CLOSE  HAL_GPIO_WritePin(A_DENITROGEN_IO_GPIO_Port, A_DENITROGEN_IO_Pin, GPIO_PIN_RESET)

//#define WA_SWITCH_OPEN   HAL_GPIO_WritePin(B_COMPRESS_IO_GPIO_Port, B_COMPRESS_IO_Pin, GPIO_PIN_SET)
//#define WA_SWITCH_CLOSE  HAL_GPIO_WritePin(B_COMPRESS_IO_GPIO_Port, B_COMPRESS_IO_Pin, GPIO_PIN_RESET)

//#define WB_SWITCH_OPEN   HAL_GPIO_WritePin(B_DENITROGEN_IO_GPIO_Port, B_DENITROGEN_IO_Pin, GPIO_PIN_SET)
//#define WB_SWITCH_CLOSE  HAL_GPIO_WritePin(B_DENITROGEN_IO_GPIO_Port, B_DENITROGEN_IO_Pin, GPIO_PIN_RESET)

#define FA_SWITCH_OPEN   HAL_GPIO_WritePin(A_COMPRESS_IO_GPIO_Port, A_COMPRESS_IO_Pin, GPIO_PIN_SET)
#define FA_SWITCH_CLOSE  HAL_GPIO_WritePin(A_COMPRESS_IO_GPIO_Port, A_COMPRESS_IO_Pin, GPIO_PIN_RESET)

#define FB_SWITCH_OPEN   HAL_GPIO_WritePin(B_COMPRESS_IO_GPIO_Port, B_COMPRESS_IO_Pin, GPIO_PIN_SET)
#define FB_SWITCH_CLOSE  HAL_GPIO_WritePin(B_COMPRESS_IO_GPIO_Port, B_COMPRESS_IO_Pin, GPIO_PIN_RESET)

#define WA_SWITCH_OPEN   HAL_GPIO_WritePin(A_DENITROGEN_IO_GPIO_Port, A_DENITROGEN_IO_Pin, GPIO_PIN_SET)
#define WA_SWITCH_CLOSE  HAL_GPIO_WritePin(A_DENITROGEN_IO_GPIO_Port, A_DENITROGEN_IO_Pin, GPIO_PIN_RESET)

#define WB_SWITCH_OPEN   HAL_GPIO_WritePin(B_DENITROGEN_IO_GPIO_Port, B_DENITROGEN_IO_Pin, GPIO_PIN_SET)
#define WB_SWITCH_CLOSE  HAL_GPIO_WritePin(B_DENITROGEN_IO_GPIO_Port, B_DENITROGEN_IO_Pin, GPIO_PIN_RESET)

#define EQ_SWITCH_OPEN   HAL_GPIO_WritePin(WASH_IO_GPIO_Port, WASH_IO_Pin, GPIO_PIN_SET)
#define EQ_SWITCH_CLOSE  HAL_GPIO_WritePin(WASH_IO_GPIO_Port, WASH_IO_Pin, GPIO_PIN_RESET)

void W_SwitchWork(SwitchParameter_TypeDef *SwitchParameter);
void F_SwitchWork(SwitchParameter_TypeDef *SwitchParameter);
void EQ_SwitchWork(SwitchParameter_TypeDef *SwitchParameter);

void Switch_Init(u8 Valve);

#endif
